name: Java CI with Gradle


  on:
    push:
      branches: [ main2 ]
    pull_request:
      branches: [ main2 ]

  jobs:
    build:
      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/set-up@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Run Backend Test
        run: ./gradlew test