name: Deploy

  on:
    push:
      branches:
        - main2
  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: akhileshns/heroku-deploy@v3.12.12
          with:
            heroku_api_key: ${{secrets.HEROKU_API_KEY}}
            heroku_app_name: "boot-deploy"
            heroku_email: "s0543834@htw-berlin.de"